### ISSUE TITLE
How do I add default  values to the properties object in appInsights.trackEvent?

### ISSUE THREAD

**Issue by arunmmanoharan** [aaronpowell/react-app-insights#8]
Hi, I would like to know which user clicked the button. Right now I am getting the value from the store and sending it. However, I need to connect a lot  of components to the redux-store just to get the userId. Can the userId be set to default somewhere?

I followed your tutorial from here: https://www.aaron-powell.com/posts/2019-10-04-implementing-monitoring-in-react-using-appinsights/

Below is my code:

    appInsights.trackEvent({name: 'Client clicked', properties: {id: this.props.profile && this.props.profile.User.id, clientId: this.props.client.id}})

Please advice.

**Comment by aaronpowell** [comment]
Do you want to make the call to appInsights as a step in the redux action, or from the component itself?

**Comment by arunmmanoharan** [comment]
From the file itself. I wrote a wrapper function which does it.


    export const appInsightsTracker = (name: string, properties?: {}) => {
      const customProperties = {
        UserId: profileData && profileData.User.id,
        ...properties
      }
      return appInsights.trackEvent({name, properties: customProperties})
    }

Now I just call appInsightsTracker.

Thanks a lot for this awesome library.

**Comment by arunmmanoharan** [comment]
@aaronpowell Is there a way I can default populate the login userId? I tried using both of these:

ai.context.user.setAuthenticatedUserContext(profileData ? profileData.User.id.toString(10) : '');
ai.context.user.authenticatedId = profileData ? profileData.User.id.toString(10) : '';

Still the value from my cache gets setup as the user id. Please advice.

**Comment by aaronpowell** [comment]
I'm closing this issue as it's not the right place for a Q&A. I'd encourage you to ask on [StackOverflow](https://stackoverflow.com/search?q=monitoring) as recommended in the [Azure Monitor](https://docs.microsoft.com/azure/azure-monitor/?WT.mc_id=-github-aapowell) docs.
